services:
  mysql:
    image: mysql:8.0
    container_name: oscar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: oscar
      MYSQL_USER: oscar_user
      MYSQL_PASSWORD: oscar_password
    ports:
      - "3306:3306"
    volumes:
      - oscar_mysql_data:/var/lib/mysql
      - ./database_backend/sql/init:/docker-entrypoint-initdb.d
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  oscar_mysql_data: