spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/oscar?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: oscar_user
    password: oscar_password
    driver-class-name: com.mysql.cj.jdbc.Driver

oscar:
  resource-root: ${OSCAR_RESOURCE_ROOT:/data/oscar}
